basePath: /
host: localhost:8082
info:
  contact: {}
  description: API Server for smart filter
  title: Todo App API
  version: "1.0"
paths: {}
securityDefinitions:
  Authorization:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
